-- Migration 009 normalized lifecycle columns on every existing user-management
-- row. Those trigger-generated no-op audit events were recorded with the
-- generic direct-SQL source. Reclassify only the events generated in migration
-- 009's application window; retain genuine direct database changes unchanged.
CREATE TABLE IF NOT EXISTS schema_migrations (
    version text PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TRIGGER IF EXISTS event_history_reject_update_delete ON event_history;

UPDATE event_history AS event
SET source = 'migration',
    metadata = event.metadata || jsonb_build_object(
        'source_attribution_backfill',
        jsonb_build_object(
            'migration', '015_reclassify_lifecycle_normalization_events',
            'previous_source', 'database',
            'originating_migration', '009_user_management_lifecycle',
            'basis', 'trigger event generated by lifecycle normalization update'
        )
    )
FROM schema_migrations AS lifecycle_migration
WHERE lifecycle_migration.version = '009_user_management_lifecycle'
  AND event.source = 'database'
  AND event.actor_type = 'system'
  AND event.actor_user_id IS NULL
  AND event.request_id IS NULL
  AND event.operation = 'UPDATE'
  AND event.entity_type IN ('org_unit', 'user', 'role')
  AND cardinality(event.changed_fields) = 0
  AND event.occurred_at BETWEEN
      lifecycle_migration.applied_at - interval '1 second'
      AND lifecycle_migration.applied_at + interval '1 second';

CREATE TRIGGER event_history_reject_update_delete
BEFORE UPDATE OR DELETE ON event_history
FOR EACH ROW EXECUTE FUNCTION reject_event_history_mutation();

INSERT INTO schema_migrations(version)
VALUES ('015_reclassify_lifecycle_normalization_events')
ON CONFLICT(version) DO NOTHING;
