BEGIN;

SELECT set_config('app.actor_type','automated_process',true),
       set_config('app.event_source','migration',true),
       set_config('app.change_reason','Install the approved internationalization Phase 1 foundation',true),
       set_config('app.event_metadata','{"migration":"019_add_internationalization_foundation"}',true);

CREATE TABLE supported_languages (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    language_tag text NOT NULL UNIQUE,
    english_name text NOT NULL,
    native_name text NOT NULL,
    direction text NOT NULL,
    is_enabled boolean NOT NULL DEFAULT true,
    is_default boolean NOT NULL DEFAULT false,
    formatting_config jsonb NOT NULL DEFAULT '{}'::jsonb,
    catalogue_revision bigint NOT NULL DEFAULT 1,
    date_created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version bigint NOT NULL DEFAULT 1,
    CONSTRAINT supported_languages_tag_shape CHECK (
        language_tag ~ '^[A-Za-z]{2,3}(-[A-Za-z0-9]{2,8})*$'
    ),
    CONSTRAINT supported_languages_english_name_not_blank CHECK (btrim(english_name) <> ''),
    CONSTRAINT supported_languages_native_name_not_blank CHECK (btrim(native_name) <> ''),
    CONSTRAINT supported_languages_direction_valid CHECK (direction IN ('ltr','rtl')),
    CONSTRAINT supported_languages_default_enabled CHECK (NOT is_default OR is_enabled),
    CONSTRAINT supported_languages_formatting_object CHECK (jsonb_typeof(formatting_config) = 'object'),
    CONSTRAINT supported_languages_revision_positive CHECK (catalogue_revision > 0),
    CONSTRAINT supported_languages_version_positive CHECK (version > 0)
);
CREATE UNIQUE INDEX supported_languages_one_default_idx
    ON supported_languages ((is_default)) WHERE is_default;
CREATE UNIQUE INDEX supported_languages_tag_ci_unique ON supported_languages(lower(language_tag));

INSERT INTO supported_languages(
    language_tag,english_name,native_name,direction,is_enabled,is_default,formatting_config
) VALUES
    ('en','English','English','ltr',true,true,'{"locale":"en"}'::jsonb),
    ('ar','Arabic','العربية','rtl',true,false,'{"locale":"ar"}'::jsonb);

CREATE FUNCTION enforce_one_enabled_default_language() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    IF (SELECT count(*) FROM supported_languages WHERE is_default AND is_enabled) <> 1 THEN
        RAISE EXCEPTION USING ERRCODE='23514',MESSAGE='exactly_one_enabled_default_language_required';
    END IF;
    RETURN NULL;
END;
$$;
CREATE CONSTRAINT TRIGGER supported_languages_require_one_default
AFTER INSERT OR UPDATE OR DELETE ON supported_languages
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
EXECUTE FUNCTION enforce_one_enabled_default_language();

CREATE TABLE user_preferences (
    user_id bigint PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    language_tag text NOT NULL REFERENCES supported_languages(language_tag) ON DELETE RESTRICT,
    working_timezone text NOT NULL,
    date_created timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    date_updated timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    version bigint NOT NULL DEFAULT 1,
    CONSTRAINT user_preferences_timezone_not_blank CHECK (btrim(working_timezone) <> ''),
    CONSTRAINT user_preferences_version_positive CHECK (version > 0)
);

CREATE FUNCTION touch_localization_row() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
    NEW.date_updated := CURRENT_TIMESTAMP;
    NEW.version := OLD.version + 1;
    RETURN NEW;
END;
$$;
CREATE TRIGGER supported_languages_touch BEFORE UPDATE ON supported_languages
FOR EACH ROW EXECUTE FUNCTION touch_localization_row();
CREATE TRIGGER user_preferences_touch BEFORE UPDATE ON user_preferences
FOR EACH ROW EXECUTE FUNCTION touch_localization_row();

CREATE TRIGGER supported_languages_record_history
AFTER INSERT OR UPDATE OR DELETE ON supported_languages
FOR EACH ROW EXECUTE FUNCTION record_entity_history('supported_language');

CREATE FUNCTION record_user_preference_history() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
    old_state jsonb;
    new_state jsonb;
    changed text[];
BEGIN
    old_state := CASE WHEN TG_OP IN ('UPDATE','DELETE') THEN to_jsonb(OLD) END;
    new_state := CASE WHEN TG_OP IN ('INSERT','UPDATE') THEN to_jsonb(NEW) END;
    SELECT COALESCE(array_agg(key ORDER BY key),ARRAY[]::text[]) INTO changed
      FROM jsonb_object_keys(COALESCE(old_state,'{}'::jsonb) || COALESCE(new_state,'{}'::jsonb)) key
     WHERE old_state -> key IS DISTINCT FROM new_state -> key;
    INSERT INTO event_history(
        entity_type,entity_id,operation,actor_user_id,actor_type,source,
        request_id,correlation_id,before_state,after_state,changed_fields,reason,metadata
    ) VALUES (
        'user_preference',CASE WHEN TG_OP='DELETE' THEN OLD.user_id ELSE NEW.user_id END,
        CASE TG_OP WHEN 'INSERT' THEN 'CREATE' ELSE TG_OP END,
        NULLIF(current_setting('app.user_id',true),'')::bigint,
        COALESCE(NULLIF(current_setting('app.actor_type',true),''),'automated_process'),
        COALESCE(NULLIF(current_setting('app.event_source',true),''),'database'),
        NULLIF(current_setting('app.request_id',true),'')::uuid,
        NULLIF(current_setting('app.correlation_id',true),'')::uuid,
        old_state,new_state,changed,
        NULLIF(current_setting('app.change_reason',true),''),
        COALESCE(NULLIF(current_setting('app.event_metadata',true),'')::jsonb,'{}'::jsonb)
    );
    RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END;
END;
$$;
CREATE TRIGGER user_preferences_record_history
AFTER INSERT OR UPDATE OR DELETE ON user_preferences
FOR EACH ROW EXECUTE FUNCTION record_user_preference_history();

INSERT INTO privileges(code,name,description,category,is_reserved,account_type_restriction) VALUES
 ('localization.administer','Administer Localization','Manage supported languages and translation catalogues.','administration',true,'person'),
 ('classification_scheme.modify_metadata','Modify Classification Scheme Metadata','Modify multilingual names and descriptions for classification schemes.','administration',false,'person'),
 ('classification.modify_metadata','Modify Classification Metadata','Modify multilingual names and descriptions for classifications.','administration',false,'person'),
 ('user.modify_metadata','Modify User Metadata','Modify multilingual names and descriptions for users.','administration',false,'person'),
 ('role.modify_metadata','Modify Role Metadata','Modify multilingual names and descriptions for roles.','administration',false,'person'),
 ('org_unit.modify_metadata','Modify Organization Unit Metadata','Modify multilingual names and descriptions for organization units.','administration',false,'person'),
 ('security_level.modify_metadata','Modify Security Level Metadata','Modify multilingual names and descriptions for security levels.','administration',false,'person')
ON CONFLICT DO NOTHING;

INSERT INTO profile_privileges(profile_id,privilege_id)
SELECT profile.id,privilege.id
FROM profiles profile CROSS JOIN privileges privilege
WHERE (privilege.code='localization.administer' AND profile.code IN ('ALL_PRIVS','SYS_ADMIN'))
   OR (privilege.code IN (
       'classification_scheme.modify_metadata','classification.modify_metadata',
       'user.modify_metadata','role.modify_metadata','org_unit.modify_metadata',
       'security_level.modify_metadata'
   ) AND profile.code='ALL_PRIVS')
ON CONFLICT DO NOTHING;

INSERT INTO schema_migrations(version)
VALUES ('019_add_internationalization_foundation') ON CONFLICT DO NOTHING;

COMMIT;
