"""Generate the root API template from the authoritative deployment template."""
import argparse
import ast
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'backend/services/api/deploy/api.env.example'
TARGET = ROOT / '.env.example.api'
HEADER = '# Generated by tools/sync_api_env_template.py; edit the deployment template.\n'


def check_api_settings():
    """Check literal consumers and the known dynamically named messaging limits."""
    readers = {'os.getenv', 'os.environ.get', 'required_environment',
               'integer_environment', 'boolean_environment', 'float_environment',
               'choice_environment'}
    keys = set()
    api = ROOT / 'backend/services/api'
    for path in api.rglob('*.py'):
        if any(part in {'.venv', 'tests', '__pycache__'} for part in path.parts):
            continue
        tree = ast.parse(path.read_text(encoding='utf-8'))
        for node in ast.walk(tree):
            if isinstance(node, ast.Call) and node.args and ast.unparse(node.func) in readers:
                key = node.args[0]
                if isinstance(key, ast.Constant) and isinstance(key.value, str):
                    keys.add(key.value)
        if path == api / 'messaging/config.py':
            for node in tree.body:
                if isinstance(node, ast.Assign) and any(
                    isinstance(target, ast.Name) and target.id == 'DEFAULTS'
                    for target in node.targets
                ):
                    keys.update('MESSAGING_' + key for key in ast.literal_eval(node.value))
    documented = set(re.findall(r'^\s*(?:#\s*)?([A-Z][A-Z0-9_]*)=',
                                SOURCE.read_text(encoding='utf-8'), re.MULTILINE))
    missing = keys - documented
    if missing:
        raise SystemExit('API settings absent from the deployment template: ' + ', '.join(sorted(missing)))
    print(f'All {len(keys)} API environment settings are documented in the deployment template.')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail if the generated template has drifted.')
    args = parser.parse_args()
    expected = HEADER + SOURCE.read_text(encoding='utf-8')
    if args.check:
        check_api_settings()
        if not TARGET.exists() or TARGET.read_text(encoding='utf-8') != expected:
            parser.exit(1, 'API environment templates differ. Run python3 tools/sync_api_env_template.py\n')
        print('API environment templates agree.')
    else:
        TARGET.write_text(expected, encoding='utf-8')
        print('Updated .env.example.api from the deployment template.')


if __name__ == '__main__':
    main()
